###Get and save token from keycloak
POST https://localhost:8443/realms/keycloak_example/protocol/openid-connect/token
Content-Type: application/x-www-form-urlencoded

client_id=keycloak_example&username=admin&password=admin&grant_type=password

> {% client.global.set("auth_token", response.body.access_token); %}

###Get for endpoint which required authentication
GET http://localhost:9000/test/user
Authorization: Bearer {{auth_token}}


###Test endpoint which required authentication without token
GET http://localhost:9000/test/user

###Test endpoint which required authentication and ROLE_ADMIN
GET http://localhost:9000/test/admin
Authorization: Bearer {{auth_token}}


###Test endpoint - permitAll without required authentication
GET http://localhost:9000/test/permitAll
